include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - android/**
    - ios/**
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - lib/core/l10n/generated/**
    - web/**
    - windows/**
    - macos/**
    - linux/**
  errors:
    # Treat these as warnings only, not errors
    deprecated_member_use: warning

linter:
  rules:
    prefer_const_constructors: true
    prefer_final_fields: true
    avoid_unnecessary_containers: true
    use_key_in_widget_constructors: true
